<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="EditDbForm.aspx.cs" Inherits="ThirdTask.EditDbForm" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
        </div>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:CompanyDbConnectionString %>" 
                           SelectCommand="SELECT [Id], [User], [Product], [Price], [Qty], [OrderTime] FROM [Orders]"
                           InsertCommand="INSERT INTO [Orders] ([User], Product, Price, Qty) VALUES (@User, @Product, @Price, @Qty)"
                           UpdateCommand="UPDATE [Orders] SET [User]=@User, Product=@Product, Price=@Price, Qty=@Qty WHERE Id=@Id"
                           DeleteCommand="Delete FROM [Orders] Where Id=@Id">
            <InsertParameters>
                <asp:ControlParameter Name="User" ControlID="UserBox" Type="Int32" />
                <asp:ControlParameter Name="Product" ControlID="ProductBox" Type="String" />
                <asp:ControlParameter Name="Price" ControlID="PriceBox" Type="Decimal" />
                <asp:ControlParameter Name="Qty" ControlID="QtyBox" Type="Int32" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="Id" Type="Int32" />
                <asp:Parameter Name="User" Type="Int32" />
                <asp:Parameter Name="Product" Type="String" />
                <asp:Parameter Name="Price" Type="Decimal" />
                <asp:Parameter Name="Qty" Type="Int32" />
            </UpdateParameters>
            <DeleteParameters>
                <asp:Parameter Name="Id" Type="Int32" />
            </DeleteParameters>
        </asp:SqlDataSource>
        <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:CompanyDbConnectionString %>" 
                           SelectCommand="SELECT [Id], [FirstName], [LastName], [Phone] FROM [Users]"
                           InsertCommand="INSERT INTO [dbo].[Users] (FirstName, LastName, Phone) VALUES (@FirstName, @LastName, @Phone)"
                           UpdateCommand="UPDATE [Users] SET FirstName=@FirstName, LastName=@LastName, Phone=@Phone WHERE Id=@Id"
                           DeleteCommand="Delete FROM [Users] Where Id=@Id">
            <InsertParameters>
                <asp:ControlParameter Name="FirstName" ControlID="FirstNameBox" Type="String" />
                <asp:ControlParameter Name="LastName" ControlID="LastNameBox" Type="String" />
                <asp:ControlParameter Name="Phone" ControlID="PhoneBox" Type="String" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="Id" Type="Int32" />
                <asp:Parameter Name="FirstName" Type="String" />
                <asp:Parameter Name="LastName" Type="String" />
                <asp:Parameter Name="Phone" Type="String" />
            </UpdateParameters>
            <DeleteParameters>
                <asp:Parameter Name="Id" Type="Int32" />
            </DeleteParameters></asp:SqlDataSource>
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
                      AutoGenerateEditButton="True" DataSourceID="SqlDataSource1" ShowHeaderWhenEmpty="True"  
                      EmptyDataText="No records has been added." DataKeyNames="Id">
            <Columns>
                <asp:BoundField DataField="User" HeaderText="User" SortExpression="User" />
                <asp:BoundField DataField="Product" HeaderText="Product" SortExpression="Product" />
                <asp:BoundField DataField="Price" HeaderText="Price" SortExpression="Price" />
                <asp:BoundField DataField="Qty" HeaderText="Qty" SortExpression="Qty" />
            </Columns>
        </asp:GridView>
        <table border="1" cellpadding="0" cellspacing="0" style="border-collapse: collapse">
            <tr>
                <td style="width: 150px">
                    User:<br />
                    <asp:TextBox ID="UserBox" runat="server" Width="140" />
                </td>
                <td style="width: 150px">
                    Product:<br />
                    <asp:TextBox ID="ProductBox" runat="server" Width="140" />
                </td>
                <td style="width: 150px">
                    Price:<br />
                    <asp:TextBox ID="PriceBox" runat="server" Width="140" />
                </td>
                <td style="width: 150px">
                    Qty:<br />
                    <asp:TextBox ID="QtyBox" runat="server" Width="140" />
                </td>
                <td style="width: 100px">
                    <asp:Button ID="btnAdd" runat="server" Text="Add" OnClick="Insert" />
                </td>
            </tr>
        </table>
        <asp:GridView ID="GridView2" runat="server" AutoGenerateColumns="False" AutoGenerateEditButton="True" AutoGenerateDeleteButton="True"
                      DataSourceID="SqlDataSource2" ShowHeaderWhenEmpty="True"
                      DataKeyNames="Id" EmptyDataText="No records has been added.">
            <Columns>
                <asp:BoundField DataField="Id" HeaderText="Id" SortExpression="Id" />
                <asp:BoundField DataField="FirstName" HeaderText="FirstName" SortExpression="FirstName" />
                <asp:BoundField DataField="LastName" HeaderText="LastName" SortExpression="LastName" />
                <asp:BoundField DataField="Phone" HeaderText="Phone" SortExpression="Phone" />
            </Columns>
        </asp:GridView>
        <table border="1" cellpadding="0" cellspacing="0" style="border-collapse: collapse">
            <tr>
                <td style="width: 150px">
                    FirstName:<br />
                    <asp:TextBox ID="FirstNameBox" runat="server" Width="140" />
                </td>
                <td style="width: 150px">
                    LastName:<br />
                    <asp:TextBox ID="LastNameBox" runat="server" Width="140" />
                </td>
                <td style="width: 150px">
                    Phone:<br />
                    <asp:TextBox ID="PhoneBox" runat="server" Width="140" />
                </td>
                <td style="width: 100px">
                    <asp:Button ID="btnAdd2" runat="server" Text="Add" OnClick="Insert2" />
                </td>
            </tr>
        </table>
    </form>
</body>
</html>
